[package]
name = "blender-launcher"
description = "Launcher and version manager for Blender"
version = "0.1.0"
authors = ["Alexander Chaplin Braz <contact@alexchaplinbraz.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
bincode = "1.3"
bzip2 = "0.4"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
derive_deref = "1.1"
device_query = "0.2"
directories-next = "2.0"
flate2 = "1.0"
iced = { git = "https://github.com/hecrj/iced", rev = "8d882d787e6b7fd7c2435f42f82933e2ed904edf" }
iced_futures = { git = "https://github.com/hecrj/iced", rev = "8d882d787e6b7fd7c2435f42f82933e2ed904edf" }
indicatif = "0.15"
itertools = "0.10"
lazy_static = "1.4"
msgbox = "0.6"
natord = "1.0"
prettytable-rs = "0.8"
regex = "1.4"
reqwest = "0.11"
select = "0.5"
serde = { version = "1.0", features = ["derive"] }
tar = "0.4"
timeago = "0.2"
tokio = { version = "1.0", features = ["fs", "io-util", "macros", "rt-multi-thread"] }
xz2 = "0.1"
zip = "0.5"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["wincon"] }
