[package]
name = "blender-launcher"
description = "Launcher and version manager for Blender"
version = "0.1.0"
authors = ["Alexander Chaplin Braz <contact@alexchaplinbraz.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
bincode = "1.3"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
derive_deref = "1.1"
device_query = "0.2"
directories-next = "2.0"
iced = "0.3"
iced_futures = "0.3"
indicatif = "0.15"
itertools = "0.10"
lazy_static = "1.4"
msgbox = "0.6"
natord = "1.0"
prettytable-rs = "0.8"
regex = "1.4"
reqwest = "0.11"
select = "0.5"
serde = { version = "1.0", features = ["derive"] }
timeago = "0.3"
tokio = { version = "1.0", features = ["fs", "io-util", "macros", "rt-multi-thread"] }

[target.'cfg(target_os = "linux")'.dependencies]
bzip2 = "0.4"
flate2 = "1.0"
tar = "0.4"
xz2 = "0.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["wincon"] }
zip = "0.5"
