[package]
name = "blender-launcher"
description = "Launcher and version manager for Blender"
version = "0.1.0"
authors = ["Alexander Chaplin Braz <contact@alexchaplinbraz.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10"
select = "0.5"
tokio = { version = "0.2", features = ["full"] }
clap = "2.33"
config = "0.10"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
