[package]
name = "blender-launcher"
version = "0.1.0"
authors = ["Alexander Chaplin Braz <contact@alexchaplinbraz.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
select = "0.5"
tokio = { version = "0.2", features = ["full"] }
